spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/parking-control  #passando a url para conexão com o banco
    username: postgres
    password: banco123
    driver-class-name: org.postgresql.Driver
  jpa:                                            #para mapear de forma automática nossa base de dados                                                      
    hibernate.ddl-auto: update                    # entidades, colunas e etc...
    properties.hibernate.jdbc.lob.non_contextual_creation: true   #desabilitamos para não haver conflitos devido aos metadados do hiber.
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    
    
  
